server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

  cloud:
    config:
      enabled: false
    import-check:
      enabled: false
